/* empty css                      */import{a as S,S as q}from"./assets/vendor-dsYlHsC8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const P="50804443-2b846a940781baef8affcab62",$="https://pixabay.com/api/";let i=1,d="";async function h(t){t!==d&&(i=1,d=t);const o={key:P,q:d,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:40},n=await S.get($,{params:o});return i+=1,n.data}function O(){i=1}const m=document.querySelector(".gallery");let u=null;function p(t){const o=t.map(({webformatURL:n,largeImageURL:a,tags:e,likes:r,views:s,comments:v,downloads:w})=>`
        <a class="photo-card" href="${a}">
          <img src="${n}" alt="${e}" loading="lazy" />
          <div class="info">
            <p><b>Likes:</b> ${r}</p>
            <p><b>Views:</b> ${s}</p>
            <p><b>Comments:</b> ${v}</p>
            <p><b>Downloads:</b> ${w}</p>
          </div>
        </a>
      `).join("");m.insertAdjacentHTML("beforeend",o),u?u.refresh():u=new q(".gallery a")}function E(){m.innerHTML=""}const H=document.querySelector("#search-form");document.querySelector(".gallery");const c=document.querySelector(".load-more"),y=document.querySelector(".loader");let g="",f=0,l=0;H.addEventListener("submit",async t=>{t.preventDefault();const o=t.currentTarget.elements.searchQuery.value.trim();if(o){E(),c.classList.add("hidden"),b();try{O(),g=o;const n=await h(o);f=n.totalHits,l=n.hits.length,p(n.hits),l<f&&c.classList.remove("hidden")}catch(n){console.error(n)}finally{L()}}});c.addEventListener("click",async()=>{b();try{const t=await h(g);p(t.hits),l+=t.hits.length,x(),l>=f&&(c.classList.add("hidden"),alert("We're sorry, but you've reached the end of search results."))}catch(t){console.error(t)}finally{L()}});function b(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}function x(){const{height:t}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
